### ISSUE TITLE
This code is not working for me 

### ISSUE THREAD

**Issue by 9602428** [SegoCode/Reg-importer#1]
Dear Developer , 

 I am trying reard the vlaues of REGEDIT and update them using this code, it is not working -can you please help ?
KR,
Basker
I can be conatcted at basker.gummadi@gmail.com

**Comment by SegoCode** [comment]
No notification was show for this issue in my github feed, I am very sorry 😟 
If you still need help with this, tell me.

**Comment by SegoCode** [comment]
New code logic implemented b939d594c3059dfceb2cca8fb928c09d5a7f383a
